// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVM2xB_VtBoB6zGsvbpv_-5_0KuRsjQ3I',
    appId: '1:948887849892:web:eef9e63f2f297592ff0f31',
    messagingSenderId: '948887849892',
    projectId: 'push-notif-b0775',
    authDomain: 'push-notif-b0775.firebaseapp.com',
    storageBucket: 'push-notif-b0775.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTu2yCupvgzFzXQVZLdd5SHipRFUXIJEY',
    appId: '1:948887849892:android:805aa917f485cc28ff0f31',
    messagingSenderId: '948887849892',
    projectId: 'push-notif-b0775',
    storageBucket: 'push-notif-b0775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaDov0h6pdM_yGGuHY8O8eKMc5mIGMQDs',
    appId: '1:948887849892:ios:a00a2caf26a12b5cff0f31',
    messagingSenderId: '948887849892',
    projectId: 'push-notif-b0775',
    storageBucket: 'push-notif-b0775.appspot.com',
    iosBundleId: 'com.example.firebasePushNotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaDov0h6pdM_yGGuHY8O8eKMc5mIGMQDs',
    appId: '1:948887849892:ios:a00a2caf26a12b5cff0f31',
    messagingSenderId: '948887849892',
    projectId: 'push-notif-b0775',
    storageBucket: 'push-notif-b0775.appspot.com',
    iosBundleId: 'com.example.firebasePushNotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVM2xB_VtBoB6zGsvbpv_-5_0KuRsjQ3I',
    appId: '1:948887849892:web:f5cdc0d890df155cff0f31',
    messagingSenderId: '948887849892',
    projectId: 'push-notif-b0775',
    authDomain: 'push-notif-b0775.firebaseapp.com',
    storageBucket: 'push-notif-b0775.appspot.com',
  );
}
